sh: 0: Can't open src/listen.sh
updating
Traceback (most recent call last):
  File "src/listen.py", line 14, in <module>
    redeploy()
  File "/home/ubuntu/shelfCheck-backend/ec2-deployment-manager/src/redeploy.py", line 17, in redeploy
    RUN(RESET)
  File "/home/ubuntu/shelfCheck-backend/ec2-deployment-manager/src/redeploy.py", line 13, in RUN
    return subprocess.check_output(action, cwd=repo_path)
NameError: name 'repo_path' is not defined
updating
Traceback (most recent call last):
  File "src/listen.py", line 14, in <module>
    redeploy()
  File "/home/ubuntu/shelfCheck-backend/ec2-deployment-manager/src/redeploy.py", line 17, in redeploy
    RUN(RESET)
  File "/home/ubuntu/shelfCheck-backend/ec2-deployment-manager/src/redeploy.py", line 13, in RUN
    return subprocess.check_output(action, cwd=REPO_PATH)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '~/Documents/shelfCheck/shelfCheck-backend': '~/Documents/shelfCheck/shelfCheck-backend'
Traceback (most recent call last):
  File "src/listen.py", line 16, in <module>
    if hasChanged():
  File "src/listen.py", line 10, in hasChanged
    subprocess.check_output(['git', 'fetch', 'origin', 'master'], cwd=REPO_PATH)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '../../../ShelfCheck-Website': '../../../ShelfCheck-Website'
